generator_ckpt: longlive_models/models/longlive_base.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
# real_name: Wan2.1-T2V-1.3B
real_name: Wan2.1-T2V-1.3B
fake_name: Wan2.1-T2V-1.3B
text_encoder_fsdp_wrap_strategy: size
# denoising_step_list:
# - 1000
# - 750
# - 500
# - 250
denoising_step_list:
- 1000
- 100
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 3.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
wandb_key: YOUR_WANDB_KEY
wandb_entity: YOUR_WANDB_ENTITY
wandb_project: YOUR_WANDB_PROJECT
sharding_strategy: hybrid_full
lr: 2.0e-06
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
data_path: longlive_models/prompts/vidprom_filtered_extended.txt
batch_size: 1
gradient_accumulation_steps: 1
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 64
log_iters: 100
max_checkpoints: 5
max_iters: 5000
save_optimizer_state: false

negative_prompt: "oversaturated, overexposed, static frame, blurry details, subtitles, style tags, artwork, painting, still image, gray cast, worst quality, low quality, jpeg artifacts, ugly, mutilated, extra fingers, poorly drawn hands, poorly drawn face, deformed, disfigured, malformed limbs, fused fingers, motionless frame, cluttered background, three legs, crowded background, walking backwards"
dfake_gen_update_ratio: 5
image_or_video_shape:
- 1
- 21 # unused in sequential training
- 16
- 60
- 104
distribution_loss: dmd
trainer: score_distillation
use_dia_forcing: true
use_motion_loss: true
gradient_checkpointing: true
num_frame_per_block: 3
load_raw_video: false
model_kwargs:
  timestep_shift: 5.0
  local_attn_size: 12
  sink_size: 3

# Visualization
vis_interval: 0
vis_ema: false
vis_video_lengths:
- 21
val_batch_size: 1
val_data_path: diadistill_models/prompts/vidprom_filtered_extended.txt

min_num_training_frames: 21
num_training_frames: 21
slice_last_frames: 21
